#!/usr/bin/python

from random import randrange

adj1 = [
"apish",
"artless",
"beslubbering",
"calumniating",
"cautelous",
"churlish",
"coldblooded",
"concupiscible",
"covetous",
"crudy",
"cuckoldly",
"deceptious",
"degenerate",
"facinerious",
"fawning",
"finical",
"fusty",
"goatish",
"gorbellied",
"greasy",
"heinous",
"incontinent",
"inexecrable",
"insolent",
"lecherous",
"lisping",
"loathly",
"lubberly",
"lumpish",
"mammering",
"musty",
"naughty",
"obscene",
"overgorged",
"panderly",
"pestiferous",
"plumpy",
"puking",
"rascally",
"reeky",
"sanctimonious",
"sickly",
"slobbery",
"sneaping",
"spongy",
"stinking",
"superserviceable",
"thrasonical",
"unhandsome",
"unwiped",
"viperous",
"wanton",
"warped",
"witless"]

adj2 = [
"bald-pated",
"barren-spirited",
"beast-eating",
"beef-witted",
"boiled-brains",
"clay-brained",
"dirt-rotten",
"dizzy-eyed",
"dull-brained",
"eye-offending",
"fat-kidneyed",
"flap-eared",
"foul-mouthed",
"half-blooded",
"hard-haired",
"hell-governed",
"hollow-eyed",
"hook-nosed",
"ill-tempered",
"knotty-pated",
"leaden-footed",
"leptus-leering",
"lily-livered",
"logger-headed",
"lust-breathed",
"motley-minded",
"mouse-eaten",
"muddy-mettled",
"nook-shotten",
"one-trunk-inheriting",
"pale-hearted",
"pigeon-livered",
"puke-stocking",
"puppy-headed",
"rank-scented",
"rug-headed",
"rump-fed",
"self-glorious",
"senseless-obstinate",
"sheep-biting",
"shrill-tongued",
"snail-paced",
"sodden-witted",
"stretch-mouthed",
"stubborn-hard",
"swag-bellied",
"tardy-gaited",
"thick-eyed",
"three-suited",
"tripe-visaged",
"under-honest",
"uneducated",
"useless",
"white-livered"]

noun = [
"abomination",
"arch-villain",
"baggage",
"bed-presser",
"blockhead",
"braggart",
"bugbear",
"bull's pizzle",
"codpiece",
"capocchia",
"cornuto",
"costermonger",
"cot-quean",
"coxcomb",
"cozener",
"dissembler",
"dullard",
"dunghill",
"fashion-monger",
"fleshmonger",
"foot-licker",
"fustilarian",
"geck",
"giglet",
"horn-beast",
"horse-back-breaker",
"idiot-worshipper",
"jack-a-nape",
"lewdster",
"malignancy",
"malmsey-butt",
"measle",
"miscreant",
"mushrump",
"ox-head",
"parasite",
"pig-nut",
"pin-buttock",
"potato finger",
"princox",
"purpose-changer",
"quatch-buttock",
"rabbit-sucker",
"rampallian",
"rat-catcher",
"ratsbane",
"rengatho",
"scum",
"scut",
"starve-lackey",
"stock-fish",
"ticklebrain",
"under-skinker",
"villiago"]

a = "a"
vowels = "aeiou"
adj1_name = adj1[randrange(0,53)]
if adj1_name[0] in vowels:
 	a = "an"
print "Thy father is %s %s, %s %s." % (
    a, adj1_name, adj2[randrange(0,53)], noun[randrange(0,53)])
